version: 2
updates:
  # Maintain GitHub Actions (checkout, setup-go, golangci-lint, etc.)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Optional: Groups updates to avoid spamming you with 10 PRs
    groups:
       actions:
         patterns:
           - "*"

  # Maintain Go Modules (go.mod)
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain Dockerfile Base Images 
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
