name: CI/CD Pipeline

# Req 1.2: Automatically triggered on push to main/develop and PRs
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  # Job 1: Quality Control (Testing & Linting)
  quality:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          #cache: true # no dependencies atm
      # Req 2.1 & Req 2.2: Linter added to pipeline
      - name: Run Linter
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: --timeout=5m

      # Req 2.1 Unit tests executed in pipeline
      - name: Run Unit Tests
        run: go test ./... -v -coverprofile=coverage.out

      # 2.3: Run static analysis scan (Only on main due to sonarcloud free only scanning that)
      - name: SonarCloud Scan
        if: github.ref == 'refs/heads/main'
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Req 2.3: Enforce Quality Gate 
      - name: SonarCloud Quality Gate Check
        if: github.ref == 'refs/heads/main'
        uses: SonarSource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b
        # Force the action to wait for the analysis result
        timeout-minutes: 5
        continue-on-error: true #sonarcloud free tier doesnt allow changing quality gate, so we keep it as a suggestion.
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # Job 2: Build & Package (Req 2.2: Produces working software)
  build:
    name: Build Container
    needs: quality 
    runs-on: ubuntu-latest

    # Grant permission to push tags back to the repo
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          # Fetch all history so the tagger knows what the previous version was
          fetch-depth: '0'
      - name: Bump version and push tag
        if: github.ref == 'refs/heads/main'
        id: tag_version
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      # Req 2.4: Code is packaged with dependencies using Docker and tag version
      - name: Build Docker Image 
        run: |
          TAG_NAME=${{ steps.tag_version.outputs.new_tag }}
          if [ -z "$TAG_NAME" ]; then TAG_NAME=${{ github.sha }}; fi
          
          docker build -t devops-app:$TAG_NAME .

  # Job 3: Verify (Smoke Test)
  verify-deployment:
    name: Verify Production
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Wait for Render Deployment
        run: sleep 120 

      - name: Smoke Test - Check HTTP Status
        env:
          TARGET_URL: ${{ secrets.PROD_URL }}
        run: |
          echo "Checking health of $TARGET_URL..."
          # -f fails the script if the HTTP code is 400+ or 500+
          curl -f -s $TARGET_URL > /dev/null
          echo "Smoke Check Passed: Website is reachable!"

