name: CI/CD Pipeline

# Req 1.2: Automatically triggered on push to main/develop and PRs
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  # Job 1: Quality Control (Testing & Linting)
  quality:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          #cache: true # no dependencies atm
      # Req 2.1 & Req 2.2: Linter added to pipeline
      - name: Run Linter
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: --timeout=5m

      # Req 2.1 Unit tests executed in pipeline
      - name: Run Unit Tests
        run: go test ./... -v -coverprofile=coverage.out

      # 2.3: Run static analysis scan (Only on main due to sonarcloud free only scanning that)
      - name: SonarCloud Scan
        if: github.ref == 'refs/heads/main'
        uses: SonarSource/sonarqube-scan-action@a31c939c4d9290072c4533038622b7d44866f281
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # Job 2: Build & Package (Req 2.2: Produces working software)
  build:
    name: Build Container
    needs: quality 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      # Req 2.4: Code is packaged with dependencies using Docker
      - name: Build Docker Image
        run: docker build -t devops-app:${{ github.sha }} .

